name: employee_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+13

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  http: ^1.6.0
  shared_preferences: ^2.5.4
  camera: ^0.12.0+1
  permission_handler: ^12.0.1
  intl: ^0.20.2
  mobile_scanner: ^7.2.0
  printing: ^5.14.3
  image_picker: ^1.2.1
  audioplayers: ^6.6.0
  device_info_plus: ^12.4.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^21.0.0
  geolocator: ^14.0.2
 
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash:

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/sounds/hrmsattendanceringtone.aac

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/logo1.jpg"


  adaptive_icon_foreground: "assets/logo1.jpg"

  remove_alpha_ios: true

# flutter_native_splash:
  # color: "#ffffff"   
  # image: assets/splash_logo.png

  # android: true
  # ios: true

  # android_12:
    # image: assets/splash_logo.png
    # color: "#ffffff"