name: employee_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  http: ^1.6.0
  shared_preferences: ^2.5.4
  camera: ^0.12.0+1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  mobile_scanner: ^7.2.0
  printing: ^5.14.3
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ✅ CORRECT place
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash:

flutter:
  uses-material-design: true

  assets:
    - assets/

# ✅ IMPORTANT: flutter ke bahar hona chahiye
flutter_icons:
  android: true
  ios: true
  image_path: "assets/ICON.jpeg"

flutter_native_splash:
  color: "#ffffff"   # background color
  image: assets/ICON.jpeg # your logo

  android: true
  ios: true

  android_12:
    image: assets/ICON.jpeg
    color: "#ffffff"